[tool.pip-tools]
allow-unsafe = true  # weird outdated default
generate-hashes = false  # pip bug https://github.com/pypa/pip/issues/9243
resolver = "backtracking"  # modern depresolver
strip-extras = true  # so that output files are true pip constraints
